function rmsandbox( varargin )
    if ~isempty( ver( 'maven' ) )
        fx.maven.command.rmsandbox( varargin{:} );
    else
        thisPath = fileparts( mfilename( 'fullpath' ) );
        rmpath( fullfile(...
            thisPath,...
            'code',...
            'maven' ) );
        rmpath( fullfile(...
            thisPath,...
            'test' ) );
    end
end
