classdef WithFailingTest < fx.maven.test.WithSampleSandbox
    
    methods( TestMethodSetup )
        
        function updateForFailingTests( this )
            copyfile( ...
                fullfile( maventestroot, 'sample', 'failingpom.xml' ), ...
                fullfile( this.Root, 'pom.xml' ) );
            copyfile(...
                fullfile( maventestroot, 'sample', 'prjfile.prj' ),...
                fullfile( this.Root, 'code', this.ArtifactId, 'prjfile.prj' ) );
            copyfile(...
                fullfile( maventestroot, 'sample', 'prjFileExist.m' ),...
                fullfile( this.Root, 'code', this.ArtifactId, 'prjFileExist.m' ) );
            packagePath = cellfun( @(str) sprintf( '+%s', str ), this.ParentPackages,...
                'UniformOutput', false );
            mkdir( fullfile( this.Root, 'test', packagePath{:}, sprintf( '+%s', this.ArtifactId ), '+failingTestOncePackaged' ) );
            copyfile(...
                fullfile( maventestroot, 'sample', 'tprjFileExist.m' ),...
                fullfile( this.Root, 'test', packagePath{:}, sprintf( '+%s', this.ArtifactId ), '+failingTestOncePackaged', 'tprjFileExist.m' ) );
            mkdir( fullfile( this.Root, 'test', packagePath{:}, sprintf( '+%s', this.ArtifactId ), '+badTests' ) );
            copyfile(...
                fullfile( maventestroot, 'sample', 'tBadTest.m' ),...
                fullfile( this.Root, 'test', packagePath{:}, sprintf( '+%s', this.ArtifactId ), '+badTests', 'tBadTest.m' ) );
        end
        
    end
    
end