function mustBeEmptyDirectory( path )
    entries = dir( path );
    filtered = { ...
        '.git', ...
        '.svn', ...
        };
    match = ismember( {entries.name}, filtered );
    entries(match) = [];
    isEmpty = numel( entries ) == 2 &...
        all( ismember( {entries.name}, {'.', '..'} ) );
    assert( isEmpty,...
        'Maven:DirNotEmpty',...
        'The path "%s" is not empty.',...
        path );
end