function mksandbox( varargin )
    parser = inputParser();
    parser.addOptional( 'ArtifactId', 'myapp', ...
        @(x) validateattributes( x, {'char'}, {'scalartext'} ) );
    parser.addOptional( 'GroupId', 'fx', ...
        @(x) validateattributes( x, {'char'}, {'scalartext'} ) );
    parser.addOptional( 'Path', pwd, ...
        @fx.maven.util.mustBeValidPath );
    parser.parse( varargin{:} );
    inputs = parser.Results;
    fx.maven.ToolboxSandbox.initialize( ...
        fx.maven.util.getFullPath( inputs.Path ), ...
        'GroupId', inputs.GroupId, ...
        'ArtifactId', inputs.ArtifactId );
end