function packagesandbox( varargin )
    parser = inputParser;
    parser.addOptional( 'Path', pwd,...
        @fx.maven.util.mustBeValidPath );
    parser.addParameter( 'OutputFile', '',...
        @fx.maven.util.mustBeValidPath );
    parser.parse( varargin{:} );
    inputs = parser.Results;
    sandbox = fx.maven.ToolboxSandbox( inputs.Path );
    if any( strcmp( 'OutputFile', parser.UsingDefaults ) )
        inputs.OutputFile = fullfile(...
            sandbox.Root,...
            sprintf( '%s v%s.mltbx',...
            sandbox.Name,...
            sandbox.Version ) );
    end
    sandbox.package( inputs.OutputFile );
end